version: "3.9"

networks:
  graphqlapi:

services:
  database:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=graphqlapi
    volumes:
      - ./.docker/data/postgres/data:/var/lib/postgresql/data
    networks:
      - graphqlapi
